### ISSUE TITLE
[enhancement]: add audio sample rate setting

### ISSUE THREAD

**Issue by butaca** [homebridge-eufy-security/plugin#127]
### Describe the solution you'd like

The audio streams seem to have a fixed sample rate. I would like to select the sample rate when configuring the device.

**Comment by thieren** [comment]
Hi @butaca 

the normal case is that the HomeKit Controller requests the sample rate. That one is used by the plugin for now.
I am not sure whether it's that useful to change that value by the user. Would also have to test if this would break streaming because the sample rate differs to the requested one.

What exactly is your use case here?

**Comment by butaca** [comment]
The audio quality is low right now and I would like to improve it in order to better understand what's happening in the surroundings of the doorbell when watching a stream in the Home app. The Eufy app sounds much better.

I quickly looked at the code (I have no experience in home bridge plugins dev) and found this: https://github.com/homebridge-eufy-security/plugin/blob/f5224f546eb735bdfbc1010161017fd64d4d4fd2/src/accessories/streamingDelegate.ts#L161 so I thought it is fixed (didn't found where it is modified after initialization).

**Comment by thieren** [comment]
I was wrong there. You're absolutely right.
The HomeKit Controller first asks the plugin which sample rates are supported and then requests one accordingly.

I'll test a little and then will probably add your requested setting. But it could take a little. Stay tuned!

**Comment by thieren** [comment]
I added a setting to enforce a sample rate with 2.1.0-beta.14

Please try it out!

**Comment by butaca** [comment]
Thank you! :)
It seems that the source audio is reinterpreted using the configured sample rate and it sounds weird ¯\\\_(ツ)\_/¯ because -I'm guessing- the source audio has a different sample rate.

Is it possible to request the source audio with the configured sample rate?

**Comment by thieren** [comment]
As far as I know there is no way to alter the sample rate of the source.

What exactly do you mean by 'weird'? Sure, it's not the best quality and I didn't do extensive comparison on the eufy app versus HomeKit but I felt the sound was ok-ish.

The again the bitrate requested by HomeKit is usually really low (~16-20kbps). It could also help to force a higher bitrate.

**Comment by thieren** [comment]
As additional information: I have analysed the raw audio stream from my doorbell: it seems that the source has a sample rate of 32 kHz while the bitrate is something like 24 kbps.

I'll test adding the 32 kHz in the next beta.

**Comment by thieren** [comment]
I'd like to revise my last comment. the 32 kHz were from a clip I saved directly from the source stream and that I analysed using vlc. If I encode the same clip with ffmpeg, it tells me the source is 16 kHz, which makes more sense in my mind.

Anyway I will add 32 kHz anyway for good measure.

**Comment by butaca** [comment]
Thanks again.

By weird I mean unexpected pitch. This usually happens when the audio is played with a different sample rate than the actual one. And I think is the case here. If there's no way to request a specific sample rate when getting the source audio, then I don't find the usefulness of having that setting in the plugin. In fact, I thought that the setting set source sample rate.

On the other hand, the bitrate is very low and could be the cause of the low quality. It would be great if you could increase it somehow.

**Comment by thieren** [comment]
Maybe I know what you mean with unexpected pitch.

Is this only happening in the first seconds of the stream? And it is not consistent - so sometime it happens and other times not? But the rest of the audio is fine?

If so, I have experienced similar audio glitches but I'd say it is more or less the same with the official eufy app. So I'd think it's a technical limitation from eufy itself and has something to do with the audio encoding on their side.

One way to counteract that I could think of would be to omit the first 2-3 seconds of audio altogether. This way the user would not experience these glitches.

**Comment by thieren** [comment]
Strange that these versions should have resolved that. I don't think that I did much to the audio part of the processing.

Anyway I did test a bit today and would agree that the HomeKit quality is less than the eufy one, but not that much (for me at least).
I also tried to increase it manually. Unfortunately HomeKit seems to be really strict about the codec requirements for it's stream. It configures the audio to be 24kHz at 24 kbps at best. And you can't force it to be much higher since the audio then stops working altogether. Pity restrictions. :-/

**Comment by thieren** [comment]
So I've done a bit more research on the audio settings and here's what I found:

- It's true that the libfdk_aac codec that is used by default decreases the quality to some degree. I saved raw audio from the camera and encoded this with different settings. At 16kHz and 16kbps the quality was much lower but with 24kHz at 24-32kbps it was ok-ish.
- the native ffmpeg `aac`codec yields much better quality results but it seems this cannot be used in our case. At least I was not able to get it working. And I don't know if this is because it does not use the right profile (eld) or because of something else. If someone figures out the right parameters, this might be a very good alternative
- switching to a whole other codec (`opus`) was not good for me. The quality might be ok, but I experienced cut off audio and skips
- Even though Homebridge should support other codecs (PCMA, PCMU, AMR, AMR-WB, ...) these don't seem to work. I only tested PCMA and AMR-WB. But when I enabled these, streaming stopped working for me entirely. Seem that the HomeKit  controller does not support the selected audio configuration. Also the HomeKit Spec don't mention PCMU and PCMA, only AAC-eld, OPUS and AMR/AMR-WB.

Nonetheless I added much more detailed options for audio encoding. These are located in the advanced video config menu (maybe it's time to rename it). You can now choose which codec is presented to the HomeKit-Controller as supported. On top of that you can force a ffmpeg codec wo use. Then there are also settings for bitrate and samplerate. The latter is also just presented to the HomeKit Controller as supported. So it will eventually choose which sample rate should be used. Also I found that forcing the bitrate to high a value the audio will stop working altogether again. Even 32 kbps might be to high sometimes (seems also to be influenced by the samplerate setting)

So that's all I could think of for now. If anyone has additional ideas, I'm happy to test something further.

**Comment by thieren** [comment]
Is implemented with release of 2.1.0
