### ISSUE TITLE
[Bug]: Unable to view Settings GUI of plugin

### ISSUE THREAD

**Issue by nerajchand** [homebridge-eufy-security/plugin#241]
### What happened?

When i try and configure the settings of this plugin, nothing loads except for a divider bar. 
I can still edit the settings in the config file, but was hoping to troubleshoot and test something from the GUI. 
Initially when i first set this up i remember the GUI working (around 1-2 years ago). 
This is running on a Rpi4 which only runs Homebridge, so no other changes have been made to the device itself. 

I've tried numerous browsers and devices, but they all load the same thing. 
Other plugins settings gui loads fine, it's just this one plugin that won't show anything. 
Rebooting also doesn't make any difference. 
<img width="838" alt="Screenshot 2022-12-06 at 11 44 33 am" src="https://user-images.githubusercontent.com/63892814/205778635-44c25d3e-64aa-4936-871d-c7f8f5af694f.png">

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

other (UnSupported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
n/a
```

### config

```shell
n/a
```

**Comment by thieren** [comment]
Hi @nerajchand 

There has much changed in the ui since you last checked it.

Could you please check if you have updated to the latest versions of homebridge, the plugin and node?

Also is there an error message in the homebridge log when trying to access the ui?

If you know how to do it, you could also open the development tools of your browser and check the console for any error messages when opening it.
