### ISSUE TITLE
[enhancement]: Add support for more than one eufy station

### ISSUE THREAD

**Issue by Bassi44** [homebridge-eufy-security/plugin#42]
### Describe the solution you'd like

Hi,
Would be great to see that this plug-in is going to support more than one eufy stations.
In my scenario I have two stations to cover best connections for my cameras.
But with the plug-in I am only able to show one station in HomeKit.

cheers

Marc

**Comment by thieren** [comment]
Hi @Bassi44 

Unfortunately I am not able to test because I don't own two stations. But from a short look in the code it should be possible to add a second station.

Could you please supply your station models and a log output with debug logging enabled? The log should contain the information after a Homebridge restart, so that the registration process of the accessories is included.

**Comment by lenoxys** [comment]
hello, I've 3 stations on my setup (1x hub, 2x solo camera) and it works fine.

**Comment by Bassi44** [comment]
Hi @thieren,
looked like that I've got a configuration issue in my Eufy app with the user permissions. Now I can see my two homebases in HomeKit.
I will test it, but seems to work as expected.

Cheers
Marc
