### ISSUE TITLE
[enhancement]: Upgrade to Eufy Security Client 3.0.0 / Upgrade to Angular 17 / Support for Smart Lock E110 (T8503)

### ISSUE THREAD

**Issue by austin-r-brown** [homebridge-eufy-security/plugin#522]
Bropat included support for my retrofit smart lock  in Eufy Security Client 3.0.0, so I threw together a version of this plugin that successfully builds and uses that version. I figured if it was of any use to anyone I would provide my fork with those upgrades here: https://github.com/austin-r-brown/plugin/tree/master

One thing to note is that I had to remove the accordion directive in the AdvancedVideoconfigComponent template for the build to work, so that page may not work anymore until this is looked into, but I was able to get the lock working.

Hopefully this will be included in the master branch soon.

Thank you!

**Comment by lenoxys** [comment]
Hello @austin-r-brown, Saw your work... I've been worked to the very same thing last week on HKSV dev branch....
In addition I've worked to simplify next device but not relying on the device type anymore at least for the plugin branch, UI will still be depend since we need to provide picture...

If you want to have a look : 
https://github.com/homebridge-eufy-security/plugin/tree/hksv

**Comment by austin-r-brown** [comment]
@lenoxys  Oh, awsesome! Is that branch stable enough for everyday use /is there any reason not to use it?

**Comment by lenoxys** [comment]
I've video stream broken and working simplifying the code because it's harsh to maintain.... so if you're not using video stream you can use it

**Comment by austin-r-brown** [comment]
Resolved in latest version (3.0.1)
