### ISSUE TITLE
[Bug]: Cameras all disappeared with 2.1.0-beta.2

### ISSUE THREAD

**Issue by mjtarr** [homebridge-eufy-security/plugin#93]
### What happened?

Installed 2.1.0-beta.2 along with new Eufy S40. So two devices now, the new S40 and a wired 2k doorbell. Install, etc goes fine. I add new bridge to HomeKit, but no cameras appear. For either device. Nor any sensors. With prior beta doorbell was fine and showed up. The only error I get on restart is:

6/25/2022, 9:21:03 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
6/25/2022, 9:21:03 AMEufy Security BridgeLoading 1 platforms...
6/25/2022, 9:21:03 AMEufy Security BridgeBridge is running on port 51836.
6/25/2022, 9:21:06 AMEufy Security BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'indexOf')

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
6/25/2022, 9:21:03 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
6/25/2022, 9:21:03 AMEufy Security BridgeLoading 1 platforms...
6/25/2022, 9:21:03 AMEufy Security BridgeBridge is running on port 51836.
6/25/2022, 9:21:06 AMEufy Security BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'indexOf')
```

**Comment by thieren** [comment]
Hi @mjtarr 

the log output you've posted is related to homebridge starting and loading the plugins. As far as I know the plugin hasn't even done anything up to this point. So I'd guess that this issue is not related to the plugin itself.

Are there any messages from the plugin itself after this error?

What happens if you would not use the plugin in a child bridge? Could you test this?

**Comment by mjtarr** [comment]
I will test that later today. No other info in the log. And it says it is running fine. I reverted to 2.0.0 (which is the most recent stable it will let me install) and the doorbell now appears. And the S40 appears as a security alarm or something, but not a camera. I will play around tonight and report back what I find out. But to sum up:

2.1.0-beta.2 - no eufy devices, cameras etc show up

2.0.0 - doorbell camera and sensors work fine, S40 shows up as security device, but not camera

**Comment by thieren** [comment]
Ok, when you're at it please see if there is a message saying `warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1`

That's about the first message that is emited from the plugin. If this doesn't print, then I wouldn't know what could cause this coming from the plugin.

**Comment by mjtarr** [comment]
I tried again. I never get that warning message. Behaves as described in my first email. No messages from the plugin. FYI I am using HOOBS. Not sure how to "not use the plugin in a child bridge? Could you test this?" HOOBS creates a new bridge (or I can use an existing one) for each plugin. But they are all child bridges insofar as I can tell. I know, I really need to move to a normal (non-hoobs) homebridge installation. Someday with some time....

**Comment by thieren** [comment]
Unfortunately I can't really test for hoobs. So yeah, a normal homebridge installation would be easier to debug. But then again there wasn't that much changed in the versions and as said the plugin doesn't seem to even start in your case. The problem seems to lie entirely with your hoobs instance. Are there any ways to remove old cached accessories? Maybe you can clean out everything from the plugin (config, stored files, cached accessories, ...) and reinstall it? Again, sorry but I don't have hoobs myself and can't really test.

**Comment by amery78** [comment]
Hello,
same here for me, since upgrading to 2.X all cams disappeared.

Here are the logs (hopefully could help)

Loaded plugin 'homebridge-eufy-security'
08/07/2022 à 19:58:43Eufy Security BridgeRegistering platform 'homebridge-eufy-security.EufySecurity'
08/07/2022 à 19:58:43Eufy Security BridgeLoading 1 platforms...
08/07/2022 à 19:58:43Eufy Security Bridge[7/8/2022, 7:58:43 PM] [EufySecurity-2.0.1] WARN:  [33mwarning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1[39m
08/07/2022 à 19:58:43Eufy Security Bridge[7/8/2022, 7:58:43 PM] [EufySecurity-2.0.1] INFO:  [32mCountry set: US[39m
08/07/2022 à 19:58:43Eufy Security Bridge[7/8/2022, 7:58:43 PM] [EufySecurity-2.0.1] INFO:  [32mFinished initializing![39m
08/07/2022 à 19:58:43Eufy Security BridgeBridge is running on port 51836.
08/07/2022 à 19:58:44Eufy Security Bridge[7/8/2022, 7:58:44 PM] [EufySecurity-2.0.1] DEBUG: [36mdiscoveringDevices[39m
08/07/2022 à 19:58:45Eufy Security Bridge[7/8/2022, 7:58:45 PM] [EufySecurity-2.0.1] DEBUG: [36mEufyClient connected true[39m
08/07/2022 à 19:58:45Eufy Security Bridge[7/8/2022, 7:58:45 PM] [EufySecurity-2.0.1] DEBUG: [36mRefresh data from cloud and schedule next refresh.[39m
08/07/2022 à 19:58:46Eufy Security Bridge[7/8/2022, 7:58:46 PM] [EufySecurity-2.0.1] DEBUG: [36mCameraMaxLivestreamDuration: 30[39m
08/07/2022 à 19:58:46Eufy Security Bridge[7/8/2022, 7:58:46 PM] [EufySecurity-2.0.1] DEBUG: [36mFound 0 stations.[39m
08/07/2022 à 19:58:46Eufy Security Bridge[7/8/2022, 7:58:46 PM] [EufySecurity-2.0.1] DEBUG: [36mFound 0 devices.[39m
08/07/2022 à 19:58:47Eufy Security Bridge[7/8/2022, 7:58:47 PM] [EufySecurity-2.0.1] WARN:  [33mPush Closed![39m
08/07/2022 à 19:58:48Eufy Security Bridge[7/8/2022, 7:58:48 PM] [EufySecurity-2.0.1] DEBUG: [36mPush Connected![39m
08/07/2022 à 19:58:53Eufy Security Bridge[7/8/2022, 7:58:53 PM] [EufySecurity-2.0.1] DEBUG: [36mPush Connected![39m

As you can see, no specific warning on connection to my Dufy account BUT zero station and/or device found.
I'm in France but I don't think that the fact that location is set to "US" should be an issue.

Would be greeeeeat if someone can help (even if hoobs is not supported ;)).

Thank you !!

Axel

**Comment by thieren** [comment]
Hi @amery78 

Could you try again with the latest beta? The 'Found x Devices' messages is removed, so don't look for it.
Instead the devices should load dynamically.
Instead look for a `Looking for old cached accessories that seem to be outdated...` message. This will pop up about a minute after startup. So if there are no devices found until then, you can be sure that none will eventually.

You can put the output in a text file and attach it here. This would be cleaner. ;-)

Also: Is there a way to access files on the hoobs device? If so, I could point you to another log file that could help.

**Comment by amery78** [comment]
Hi @thieren, thanks a lot for your answer.
Just upgraded Eufy to 2.1.8 Beta.
You will see in the log attached that nothing happens (log in insane mode)
[eufy_logs.txt](https://github.com/homebridge-eufy-security/plugin/files/9131511/eufy_logs.txt)

Regarding you question on file access, should be possible because hoobs offers access to system through terminal (embedded into hoobs portal) or directly via SSH.

**Comment by andyrooo82** [comment]
I updated the plug-in to beta 8 however the camera didn't show up again. I had to go to HomeKit section and not show it, restart Apple TV, then shot it again. Now it's streaming ok. Will give it 24 hours or so and see if behaves itself.

**Comment by thieren** [comment]
> Hi @thieren, thanks a lot for your answer. Just upgraded Eufy to 2.1.8 Beta. You will see in the log attached that nothing happens (log in insane mode) [eufy_logs.txt](https://github.com/homebridge-eufy-security/plugin/files/9131511/eufy_logs.txt)
> 
> Regarding you question on file access, should be possible because hoobs offers access to system through terminal (embedded into hoobs portal) or directly via SSH.

So according to your log it displays the 'planned changes' message and after that nothing?

Can you share your config json?

**Comment by thieren** [comment]
> I updated the plug-in to beta 8 however the camera didn't show up again. I had to go to HomeKit section and not show it, restart Apple TV, then show it again. Now it's streaming ok. Will give it 24 hours or so and see if behaves itself.

Hey @andyrooo82 

I believe this comment belongs to #114 , right?

**Comment by thieren** [comment]
Thx for the log and config.

Please try the newest beta. If this doesn't help try also the new setting `"omitLogFiles": true`
This should prevent the plugin from trying to create a log under the specified path.

**Comment by thieren** [comment]
Just uploaded it a few minutes ago. `2.1.0-beta.9` should be visible soon.

**Comment by thieren** [comment]
Closed since this is stale. Please let me know if the issue still persists.
