### ISSUE TITLE
[bug]: Cams disapeared after upgrading to 2.0.x

### ISSUE THREAD

**Issue by DanLysk** [homebridge-eufy-security/plugin#97]
### Describe the solution you'd like

Hey guys! Thank you so much for your continued work on the Hoobs Plug in... Ever since upgrading to 2.0 of the plugin my Floodlight Cam and SoloCam S40 disappeared from the Home App view... Is this expected or am I doing something wrong? I did update to 2.01 today and still, No-go... 

Thank you again
-Dan

**Comment by thieren** [comment]
Hi @DanLysk 

Unfortunately we don't officially support hoobs, since we can't test on it. But we can try to get it working anyway...

This might be a duplicate of #93 

Can you share a little more information please?

Try to enable debug messages (`enableDetailedLogging: true` in your config) and share a log output after restarting hoobs/the plugin.

**Comment by thieren** [comment]
stale
